name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Hugging Face Token
        env:
          HF_TOKEN: ${{ secrets.HF }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "❌ HF_TOKEN is empty!"
            exit 1
          else
            echo "✅ HF_TOKEN is set with length: ${#HF_TOKEN}"
          fi

      - name: Deployment To Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: make deploy HF=$HF
