name: Continuous Deployment
on:
  workflow_call:
    secrets:
      HF_TEST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check HF_TOKEN
        env:
          HF_TEST: ${{ secrets.HF_TEST }}
        run: test -n "$HF_TEST" || (echo "HF_TOKEN is empty" && exit 1)

      - uses: actions/checkout@v3
      - name: Deployment To Hugging Face
        run: make deploy HF=${{ secrets.HF_TEST }}
