name: Continuous Deployment
on:
  workflow_call:
    secrets:
      hf_token:
        required: true

  workflow_dispatch:

permissions:
  contents: write  # Required to push changes and check out branches

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Deployment To Hugging Face
        run: make deploy HF=${{ secrets.hf_token }}
